services:
    app:
        build:
            context: .
            dockerfile: docker/php.dockerfile
        ports:
            - 8080:80
        volumes:
            - ./storage:/app/storage
            - ./.env:/app/.env
        environment:
            DB_CONNECTION: sqlite
            DB_FOREIGN_KEYS: true
            APP_USER_EMAIL: admin@example.com # Only used for seeding the database
            APP_USER_PASSWORD: admin # Only used for seeding the database
            SCRAPER_BASE_URL: http://scraper:3000 # Url to Name of the scrapper service
            AFFILIATE_ENABLED: "false" # See https://pricebuddy.jez.me/support-project.html

    scraper:
        image: amerkurev/scrapper:latest
        ports:
            - 3030:3000 # Optional, if you want to access the scrapper api from the host machine
